import {StaticRouter} from "react-router-dom/server";
import {ChunkExtractor} from '@loadable/server';
import App from "../../dist/build/App";

const express = require('express');
const fs = require('fs');
const path = require('path');
const React = require('react');
const ReactDOMServer = require('react-dom/server');
const app = express();

// This is the stats file generated by webpack loadable plugin
const statsFile = require('path').resolve('dist/loadable-stats.json')
const extractor = new ChunkExtractor({statsFile})

app.get(/\.(js|css|map|ico|png)$/, express.static(path.resolve(__dirname, '../..')));

app.use('*', (req, res) => {
    let indexHTML = fs.readFileSync(path.resolve(__dirname, '../../public/index.html'), {
        encoding: 'utf8',
    });

    const jsx = extractor.collectChunks(
        <StaticRouter location={req.originalUrl}>
            <App/>
        </StaticRouter>
    )

    let appHTML = ReactDOMServer.renderToString(jsx)

    indexHTML = indexHTML.replace('<div id="root"></div>', `<div id="root">${appHTML}</div>`)

    res.contentType('text/html');
    res.status(200);

    return res.send(indexHTML);

});

app.listen('9000', () => {
    console.log('Express server started at <http://localhost:9000>');
});